Sprint 3
eldarknz/middle.messenger.praktikum.yandex pull request #3
Opened 2023-04-02 19:40 UTC by eldarknz

2023-04-02 20:01 UTC, eldarknz commented
Я проверил все свои файлы стилей, и все они имеют расширение .scss. Я не пойму почему при тесте вылезает ошибка
```
Files with styles must have one extension. For example, .scss
FAILED
Error: Process completed with exit code 1.
```

2023-04-03 08:53 UTC, evgenygil requested changes

2023-04-03 08:53 UTC, evgenygil commented on declarations/index.d.ts
>  export {};
Для чего это экспортируется?

2023-04-03 08:53 UTC, evgenygil commented on declarations/index.d.ts
>  export type TUserData = {
Не совсем понятно почему типы, которые относятся к конкретным бизнес-сущностям лежат в глобальных декларациях в корне, мне кажется им место где-то ближе к самим сущностям

2023-04-03 08:53 UTC, evgenygil commented on src/components/sections/chatFooter/chatFooter.ts
> +                    if (target && target instanceof HTMLFormElement && state.ws) {
А разве тут может быть что-то отличное, зачем проверять дополнительно на `instanceof`

2023-04-03 08:53 UTC, evgenygil commented on src/components/sections/chatHeader/chatHeader.ts
> +                                                                if (target) {
Такой вложенные код очень трудно читать, в файле почти 700 строк кода, несколько разных функций с множеством вложенных условий, надо постараться разбить эти конструкции на отдельные элементы/блоки/файлы, слишком много логики зашито в одном месте, хотя это просто `header`

2023-04-03 08:53 UTC, evgenygil commented on src/components/sections/chatHeader/chatHeader.ts
> +    if (user && activeChatUsers && activeChatId) {
Надо использоваться ранний выход, то есть это когда мы не всю логику кладем под проходящее условие, а наоборот, в негативном случае сразу делаем return;

То есть что-то типа
```
if (!user || !activeChatUsers || !activeChatId) {
  return;
}
```

2023-04-03 08:53 UTC, evgenygil commented on src/components/sections/chatHeader/chatHeader.ts
> +            /*ws.send(JSON.stringify({
Нужно либо удалить закомментированный код либо написать зачем он был закомментирован

2023-04-03 08:53 UTC, evgenygil commented on src/components/sections/chatHeader/chatHeader.ts
> +export default ChatHeaderSection
Рекомендую посмотреть [статью](https://medium.com/@Brisstor/%D0%BF%D0%BE%D1%87%D0%B5%D0%BC%D1%83-%D0%BC%D1%8B-%D0%BE%D1%82%D0%BA%D0%B0%D0%B7%D0%B0%D0%BB%D0%B8%D1%81%D1%8C-%D0%BE%D1%82-export-default-%D0%B2-javascript-%D0%B8-%D0%B2%D0%B0%D0%BC-%D1%81%D0%BB%D0%B5%D0%B4%D1%83%D0%B5%D1%82-%D0%BF%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%B8%D1%82%D1%8C-%D1%82%D0%B0%D0%BA%D0%B6%D0%B5-cce6ac30d67b) про то почему дефолтный экспорт это не очень хорошо

2023-04-03 08:53 UTC, evgenygil commented on src/components/sections/chatHeader/chatHeader.ts
> +                                //ws.close()//deleteChat(activeChatId, ws)
Нужно либо удалить закомментированный код либо написать зачем он был закомментирован

2023-04-03 08:53 UTC, evgenygil commented on src/components/sections/chatList/chatList.ts
> +interface IChatList {
Получается часть типов/интерфейсов описана внутри прямо рядом с сущностями а другая часть лежит где-то совсем в корне, возможно стоит переструктурировать это дело

2023-04-03 08:53 UTC, evgenygil commented on src/components/sections/chatList/chatList.ts
> +        if (state.chats && (state.chats as TChatItem[]).length !== 0) {
Очень сложно читать вложенные условия с множеством компонентов внутри

2023-04-03 08:53 UTC, evgenygil commented on src/components/sections/chatMessageArea/chatMessageArea.ts
> +const getMessages = (state: Indexed) => {
Не совсем понятно что такое вообще `Indexed`, то есть название типа совсем не говорит само за себя, хотя могло бы

2023-04-03 08:53 UTC, evgenygil commented on src/components/ui/button/index.ts
> +        if (!this.props.isOutline && this.props.isLink) className += " btn-link"
Возможно тут стоит как-то оптимизировать условия, мы по 2 раза проверяем некоторые свойства, сначала на `true` потом на `false`

2023-04-03 08:53 UTC, evgenygil commented on src/components/ui/grid/index.ts
> +export const Col: FC<IColProps> = ({
Нужно удалить или написать зачем закомментирован

2023-04-03 08:53 UTC, evgenygil commented on src/components/ui/grid/index.ts
> +export class Col extends Block {
Все перемешано в этом файле, и классы и типы и интерфейсы в разном порядке

2023-04-03 08:53 UTC, evgenygil commented on src/components/ui/link/index.ts
> +        window.router!.go(this.props.href);
Почему у нас роутер хранится в `window`? В чем необходимость через `window` этим управлять?

2023-04-03 08:53 UTC, evgenygil commented on src/core/api/baseApi.ts
> +      create() { throw new Error('Not implemented'); }
Нет необходимости в этом классе, методы нигде я так понимаю не переопределены

2023-04-03 08:53 UTC, evgenygil commented on src/core/api/authApi.ts
> +class AuthAPI extends HTTPTransport {
Я вижу клас `BaseAPI`, почему тогда наследуемся сразу от `HTTPTransport` а не от `BaseAPI` ?

2023-04-03 08:53 UTC, evgenygil commented on src/core/api/httpTransport.ts
> +type HTTPRequest = (url: string, options: RequestOptions, timeout?: number) => Promise<XMLHttpRequest>;
По сути это одно и то же с верхним методом, `options` тоже может быть опциональным полем

2023-04-03 08:53 UTC, evgenygil commented on src/index.ts
> +    const user = await AuthController.checkUser()
Я видел во многих других кусках кода используется `.then()` а тут `async/await`, нужно привести к одному стилю

2023-04-05 19:14 UTC, eldarknz commented on declarations/index.d.ts
>  export {};
Убрал. Вообще я хотел, чтобы в режиме dev у меня включался дебаг режим и выводились console.log, либо console.info. Задумка была такая, но реализация кривая. Отказался от такой идеи.

2023-04-05 21:28 UTC, eldarknz commented on declarations/index.d.ts
>  export type TUserData = {
Убрал эти типы, они уже неактуальны, т.к. я их использовал для моков. Убрал лишнее из index.d.ts.

2023-04-05 21:43 UTC, eldarknz commented on src/components/sections/chatFooter/chatFooter.ts
> +                    if (target && target instanceof HTMLFormElement && state.ws) {
В принципе эта проверка тут не нужна и по логике вещей другого ничего быть не может. Изначально я решил добавить такую проверку по подобию проверок в функциях uploadChatAvatar и addNewUser в компоненте chatHeader. Там, если убрать такую проверку, то при передаче target в FormData вылезает ошибка:

```
Argument of type 'EventTarget' is not assignable to parameter of type 'HTMLFormElement'.
  Type 'EventTarget' is missing the following properties from type 'HTMLFormElement': acceptCharset, action, autocomplete, elements, and 301 more.ts(2345)
```

Поэтому я тут добавил, чтобы лишний раз не вылезали ошибки.

2023-04-05 21:51 UTC, eldarknz commented on src/components/sections/chatHeader/chatHeader.ts
> +    if (user && activeChatUsers && activeChatId) {
Сделал так. Хотя я не понимаю преимущества этого подхода в данном случае. Работать будет в обоих случаях, но при этом пишем лишнюю строчку return. Не могли бы вы пояснить.

2023-04-05 21:53 UTC, eldarknz commented on src/components/sections/chatHeader/chatHeader.ts
> +            /*ws.send(JSON.stringify({
Убрал. Не заметил.

2023-04-05 22:06 UTC, eldarknz commented on src/components/sections/chatHeader/chatHeader.ts
> +export default ChatHeaderSection
Да, я знаком с данной статьей, читал уже. Согласен, необходимо отойти от этого подхода. Экспорт по умолчанию использую просто по привычке и ради удобства. Не нравится мне, когда мы делаем именованный импорт какой-нибудь одной функции или класса, без разницы.
Например:
```
import something from "./filename";
import { something } from "./filename;
```
Первый вариант внешне для меня более привлекателен и читабелен, чем второй, т.к. во второй записи есть курли, которые мне мозолят глаза.
Или иногда помимо како-то объекта я еще импортирую какие-то вспомогаетльные вещи из одного файла.
Вот в такой записи
`import importantObject, { notImportantObject } from "./filename";`
я сразу понимаю, что importantObject несет основной функционал, а notImportantObject второстепенный.
Может конечно это привычка и мои заморочки, не спорю.

2023-04-05 23:11 UTC, eldarknz commented on src/components/sections/chatHeader/chatHeader.ts
> +export default ChatHeaderSection
Убрал все дефолтные импорты

2023-04-05 23:11 UTC, eldarknz commented on src/components/sections/chatHeader/chatHeader.ts
> +                                //ws.close()//deleteChat(activeChatId, ws)
Убрал, не заметил.

2023-04-05 23:13 UTC, eldarknz commented on src/components/ui/grid/index.ts
> +export const Col: FC<IColProps> = ({
Удалил. Не заметил.

2023-04-05 23:13 UTC, eldarknz commented on src/core/api/baseApi.ts
> +      create() { throw new Error('Not implemented'); }
Убрал.

2023-04-06 13:51 UTC, eldarknz commented on src/core/api/authApi.ts
> +class AuthAPI extends HTTPTransport {
Убпал BaseApi.

2023-04-06 13:52 UTC, eldarknz commented on src/components/sections/chatHeader/chatHeader.ts
> +                                                                if (target) {
Выполнил рефакторинг компонента, вынес логику в отдельыне компоненты.

2023-04-08 14:46 UTC, eldarknz commented on src/components/sections/chatList/chatList.ts
> +interface IChatList {
Те интерфейсы/типы, которые связаны с компонентами описаны в самих компонентах. А те интерфейсы/типы, котоыре связаны с данными описаны в types/index.ts.

2023-04-08 15:00 UTC, eldarknz commented on src/components/sections/chatList/chatList.ts
> +        if (state.chats && (state.chats as TChatItem[]).length !== 0) {
Постарался упростить.

2023-04-08 21:07 UTC, eldarknz commented on src/components/ui/button/index.ts
> +        if (!this.props.isOutline && this.props.isLink) className += " btn-link"
Изменил логику условий.

2023-04-08 23:49 UTC, eldarknz commented on src/components/ui/grid/index.ts
> +export class Col extends Block {
Переработал.

2023-04-08 23:59 UTC, eldarknz commented on src/core/api/httpTransport.ts
> +type HTTPRequest = (url: string, options: RequestOptions, timeout?: number) => Promise<XMLHttpRequest>;
Переработан.

2023-04-09 10:44 UTC, eldarknz commented on src/components/ui/link/index.ts
> +        window.router!.go(this.props.href);
Прееработал. Моя задумка была такова, чтобы иметь доступ к роутеру глобально, не засоряя компоненты лишними импортами. Почему это не стоит делать?

2023-04-09 22:46 UTC, eldarknz commented on src/index.ts
> +    const user = await AuthController.checkUser()
Переработал.

2023-04-09 22:48 UTC, eldarknz commented on src/components/ui/link/index.ts
> +        window.router!.go(this.props.href);
Прееработал. Моя задумка была такова, чтобы иметь доступ к роутеру глобально, не засоряя компоненты лишними импортами. Почему это не стоит делать?

2023-04-10 18:50 UTC, eldarknz commented
Что касается запросов к серверу для получения чатов, то мной было принято такое решение, т.к. непонятно как получать новые сообщения в других чатах. Я согласен, что это не очень хорошее решение, т.к. мы лишний раз грузим сервер. Но, если представить, что сидит пользователь в одном чате, а в другом тебе кто-то может написать. Если не запрашивать чаты, то мы не узнаем, что кто-то нам написал. Я считаю, что это недоработка API. Я так понимаю для этих целей мы как раз могли бы использовать WebSocket. Но по факту WebSocket мы используем только при обмене сообщений в выбранном чате. Может быть есть какое-то более правильно решение, чем мое, чтобы получать сообщения в других чатах в реальном времени?

2023-04-12 15:56 UTC, evgenygil commented on src/components/sections/chatFooter/chatFooter.ts
> +                    if (target && target instanceof HTMLFormElement && state.ws) {
Ну это я вижу ошибка TypeScript-а, а проверка на инстанс JS, то есть достаточно просто указать нужный тип

2023-04-12 16:56 UTC, evgenygil commented on src/components/sections/chatHeader/chatHeader.ts
> +    if (user && activeChatUsers && activeChatId) {
Работать будет, это безусловно, машине вообще все равно как написать код, если запускается и выполняется, она будет его обрабатывать. Мы пишем в продуктовых приложениях для людей, когда есть ясный и понятный ход выполнения функции это намного проще понимать и дебажить, тут человек увидит что если такие-то условия не выполняются мы сразу не продолжаем, нежели чем листать искать в коде `else` и смотреть что там происходит

2023-04-12 16:58 UTC, evgenygil commented on src/components/ui/link/index.ts
> +        window.router!.go(this.props.href);
Нет ничего плохого в импорте его в компонентах, все равно в бандле присутствует этот код, а шаринг его через `window` по сути открывает наружу все внутренности логики приложения, плюс каждый раз это обращение к `window`

2023-04-12 16:59 UTC, evgenygil commented
> Что касается запросов к серверу для получения чатов, то мной было принято такое решение, т.к. непонятно как получать новые сообщения в других чатах. Я согласен, что это не очень хорошее решение, т.к. мы лишний раз грузим сервер. Но, если представить, что сидит пользователь в одном чате, а в другом тебе кто-то может написать. Если не запрашивать чаты, то мы не узнаем, что кто-то нам написал. Я считаю, что это недоработка API. Я так понимаю для этих целей мы как раз могли бы использовать WebSocket. Но по факту WebSocket мы используем только при обмене сообщений в выбранном чате. Может быть есть какое-то более правильно решение, чем мое, чтобы получать сообщения в других чатах в реальном времени?

Можно использовать сокеты для периодической подгрузки сообщений в чатах по их идентификаторам, мы же их получается знаем

2023-04-12 17:11 UTC, evgenygil approved these changes

2023-04-12 17:11 UTC, evgenygil commented on src/components/sections/chatHeader/components/addUserModal/index.ts
> +                        const infoItem = (target as HTMLElement).closest('.user-list__info-item__addition');
Вообще наверное стоит использовать максимально специфичные селекторы, идентификаторы элементов, было бы логичнее чем использовать методы по поиску ближайших к каким-то классам

2023-04-12 17:11 UTC, evgenygil commented on src/components/sections/chatHeader/components/chatInfoBlock/index.ts
> +    } else if (userCount.toString().slice(-1) === "2" || userCount.toString().slice(-1) === "3" || userCount.toString().slice(-1) === "4") {
мы тут каждый раз заново "слайсим" строчку, можно это вынести наверх и выполнить 1 раз

2023-04-12 20:15 UTC, merged